In [1]:
import pandas as pd
import numpy as np

acc = pd.read_csv("Accelerometer.csv")
acc.drop(columns='Time (s)')
gyr = pd.read_csv("Gyroscope.csv")
gyr.drop(columns='Time (s)')

activity = pd.DataFrame(columns= ["X (m/s^2)","Y (m/s^2)","Z (m/s^2)", "X (rad/s)", "Y (rad/s)", "Z (rad/s)"])

In [2]:
activity

Empty DataFrame
Columns: [X (m/s^2), Y (m/s^2), Z (m/s^2), X (rad/s), Y (rad/s), Z (rad/s)]
Index: []

In [3]:
activity['X (m/s^2)'] = acc['X (m/s^2)'].values
activity['Y (m/s^2)'] = acc['Y (m/s^2)'].values
activity['Z (m/s^2)'] = acc['Z (m/s^2)'].values
activity['X (rad/s)'] = gyr['X (rad/s)'].values
activity['Y (rad/s)'] = gyr['Y (rad/s)'].values
activity['Z (rad/s)'] = gyr['Z (rad/s)'].values



activity["Subject"] = 2
activity["Activity"] = "Jumping"

In [4]:
activity

,X (m/s^2),Y (m/s^2),Z (m/s^2),X (rad/s),Y (rad/s),Z (rad/s),Subject,Activity
0,-7.345226,-24.955056,-3.425477,-0.083983,0.092885,-0.188556,2,Jumping
1,-8.648715,-23.425087,-2.406096,-0.079537,-0.766710,0.223857,2,Jumping
2,-3.523373,-24.986939,-3.662883,-0.138127,-0.877943,0.190594,2,Jumping
3,4.218677,-26.158553,-5.455106,-0.177167,-0.784798,-0.174076,2,Jumping
4,8.807834,-25.289011,-4.529281,-0.193196,-0.711559,-0.393005,2,Jumping
...,...,...,...,...,...,...,...,...
3011,-7.256310,-24.341182,-8.970995,-0.594234,-0.795699,-0.009559,2,Jumping
3012,-9.164093,-20.784129,-6.586004,-0.302543,-0.264977,0.263037,2,Jumping
3013,-8.298294,-21.360730,-0.299976,0.229524,0.490977,0.342450,2,Jumping
3014,-7.099287,-23.898553,3.424878,0.331372,0.726634,0.441741,2,Jumping
3015,-6.954388,-25.644073,1.322200,0.187061,0.642064,0.573217,2,Jumping

In [5]:
activity.to_csv('jaylongJumps.csv', index=False)